[package]
name = "discord-presence-jellyfin"
version = "0.1.0"
edition = "2021"

[dependencies]
discord-rich-presence = "0.2.4"
serde_json = "1.0.127"

[dependencies.reqwest]
default-features = false
features         = ["rustls-tls", "json", "blocking"]
version          = "0.12"
